// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx ./prisma/seed.ts",
  },
  // Prisma 7: la URL de la base (PostgreSQL estándar) se resuelve SIEMPRE desde
  // la variable de entorno DATABASE_URL (Supabase/Render). Sin esto, Migrate
  // no puede conectarse a la base remota.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});